### ISSUE TITLE
moduleId crashes WebPack builds

### ISSUE THREAD

**Issue by Gustorn** [akserg/ng2-slim-loading-bar#20]
The `moduleId` added in ae237f0 crashes WebPack builds with the following error message:

```
Uncaught TypeError: t.match is not a function
```

While this is a known bug in the angular compiler (angular/angular#10626), it's still something worth noting I think.

**Comment by akserg** [comment]
Will `module.id.toString()` enought to fix your problem?

**Comment by akserg** [comment]
Please use 2.0.2 to confirm that the issue was fixed.

**Comment by clementbrunel** [comment]
Works with webpack 2.1.0-beta.21 and ng2-slim-loading-bar 2.0.2.
Thanks you :)
